# Generated by Django 5.0.1 on 2024-02-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='image',
            field=models.ImageField(default='gestion_img', upload_to='gestion_img'),
        ),
    ]
