# Generated by Django 5.0.1 on 2024-02-12 01:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitacion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Descripción por defecto'),
        ),
    ]
