# Generated by Django 5.0.1 on 2024-02-12 03:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotohabitacioninformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gestion_img', upload_to='gestion_img')),
                ('descripcion', ckeditor.fields.RichTextField(default='Descripción por defecto')),
            ],
            options={
                'verbose_name': 'fotohabitacioninformation',
                'verbose_name_plural': 'fotohabitacioninformationes',
                'db_table': 'fotohabitacioninformation',
            },
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='image',
        ),
    ]
