# Generated by Django 5.0.1 on 2024-02-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_fotohabitacioninformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotohabitacioninformation',
            name='image',
            field=models.ImageField(upload_to='gestion_img'),
        ),
    ]
