# Generated by Django 5.0.1 on 2024-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_alter_fotohabitacioninformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotohabitacioninformation',
            name='title',
            field=models.CharField(default='Descripción por defecto', max_length=50),
        ),
    ]
