# Generated by Django 5.0.3 on 2024-03-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_fotohabitacioninformation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('baja', 'Gama Baja'), ('media', 'Gama Media'), ('alta', 'Gama Alta')], max_length=10),
        ),
    ]
