# Generated by Django 5.0.3 on 2024-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0007_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('baja', 'bama baja'), ('media', 'bama media'), ('alta', 'bama alta')], max_length=10),
        ),
    ]
