# Generated by Django 5.0.3 on 2024-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0008_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('baja', 'gama baja'), ('media', 'gama media'), ('alta', 'gama alta')], max_length=10),
        ),
    ]
