# Generated by Django 5.0.3 on 2024-03-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0010_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
