# Generated by Django 5.0.1 on 2024-02-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='serviciohabitacion',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='serviciohabitacion',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='ServicioHabitacion',
        ),
    ]
